/**
 * Android strings.xml support.
 * Location: res/values/strings.xml (source), res/values-{lang}/strings.xml (targets)
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs'
import { join } from 'path'
import { ProntoConfig } from '../config.js'

export interface AndroidStringsFile {
  path: string
  language: string
  strings: Record<string, string>
}

function resDir(config: ProntoConfig, cwd: string): string {
  return join(cwd, config.locale_dir ?? 'res')
}

export function parseStringsXml(content: string): Record<string, string> {
  const result: Record<string, string> = {}
  // Match <string name="key">value</string>
  const re = /<string\s+name="([^"]+)"[^>]*>([\s\S]*?)<\/string>/g
  for (const match of content.matchAll(re)) {
    const key = match[1]
    const value = match[2]
      .replace(/\\'/g, "'")
      .replace(/\\"/g, '"')
      .replace(/\\n/g, '\n')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&amp;/g, '&')
      .replace(/&quot;/g, '"')
    result[key] = value
  }
  return result
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, "\\'")
}

export function serializeStringsXml(strings: Record<string, string>): string {
  const lines = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generated by Pronto CLI -->', '<resources>']
  for (const [k, v] of Object.entries(strings)) {
    lines.push(`    <string name="${k}">${escapeXml(v)}</string>`)
  }
  lines.push('</resources>', '')
  return lines.join('\n')
}

export function discoverAndroidFiles(config: ProntoConfig, cwd: string): AndroidStringsFile[] {
  const res = resDir(config, cwd)
  if (!existsSync(res)) return []

  const sourcePath = join(res, 'values', 'strings.xml')
  if (!existsSync(sourcePath)) return []

  return [{
    path: sourcePath,
    language: config.source_language,
    strings: parseStringsXml(readFileSync(sourcePath, 'utf8')),
  }]
}

export function writeAndroidStrings(config: ProntoConfig, cwd: string, lang: string, strings: Record<string, string>): string {
  const res = resDir(config, cwd)
  // Android uses values-es, values-ja, values-fr etc.
  const dir = join(res, `values-${lang}`)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  const path = join(dir, 'strings.xml')
  writeFileSync(path, serializeStringsXml(strings), 'utf8')
  return path
}

export function getExistingAndroid(config: ProntoConfig, cwd: string, lang: string): Record<string, string> | null {
  const res = resDir(config, cwd)
  const path = join(res, `values-${lang}`, 'strings.xml')
  if (!existsSync(path)) return null
  try { return parseStringsXml(readFileSync(path, 'utf8')) } catch { return null }
}
