/**
 * iOS .strings / .stringsdict support.
 * Format: "key" = "value"; (Localizable.strings)
 * Location: <locale>.lproj/Localizable.strings
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs'
import { join } from 'path'
import { ProntoConfig } from '../config.js'

export interface StringsFile {
  path: string
  language: string
  strings: Record<string, string>
}

function stringsRoot(config: ProntoConfig, cwd: string): string {
  return join(cwd, config.locale_dir ?? '.')
}

export function discoverStringsFiles(config: ProntoConfig, cwd: string): StringsFile[] {
  const root = stringsRoot(config, cwd)
  const sourceLang = config.source_language
  const files: StringsFile[] = []

  // Walk looking for {lang}.lproj directories
  function scanDir(dir: string) {
    if (!existsSync(dir)) return
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue
      const lprojMatch = entry.name.match(/^([a-z]{2}(?:-[A-Z]{2})?)\.lproj$/)
      if (!lprojMatch) {
        // recurse one level (for Xcode project structures)
        scanDir(join(dir, entry.name))
        continue
      }
      const lang = lprojMatch[1]
      if (lang !== sourceLang) continue
      const stringsPath = join(dir, entry.name, 'Localizable.strings')
      if (!existsSync(stringsPath)) continue
      files.push({ path: stringsPath, language: lang, strings: parseStrings(readFileSync(stringsPath, 'utf8')) })
    }
  }

  scanDir(root)
  return files
}

export function parseStrings(content: string): Record<string, string> {
  const result: Record<string, string> = {}
  // Match: "key" = "value";
  const lineRe = /^\s*"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;/gm
  for (const match of content.matchAll(lineRe)) {
    const key = match[1].replace(/\\"/g, '"').replace(/\\\\/g, '\\').replace(/\\n/g, '\n')
    const value = match[2].replace(/\\"/g, '"').replace(/\\\\/g, '\\').replace(/\\n/g, '\n')
    result[key] = value
  }
  return result
}

export function serializeStrings(strings: Record<string, string>): string {
  const lines = ['/* Generated by Pronto CLI */', '']
  for (const [k, v] of Object.entries(strings)) {
    const ek = k.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
    const ev = v.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
    lines.push(`"${ek}" = "${ev}";`)
  }
  return lines.join('\n') + '\n'
}

export function writeStringsFile(config: ProntoConfig, cwd: string, lang: string, strings: Record<string, string>): string {
  const root = stringsRoot(config, cwd)
  const dir = join(root, `${lang}.lproj`)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  const path = join(dir, 'Localizable.strings')
  writeFileSync(path, serializeStrings(strings), 'utf8')
  return path
}

export function getExistingStrings(config: ProntoConfig, cwd: string, lang: string): Record<string, string> | null {
  const root = stringsRoot(config, cwd)
  const path = join(root, `${lang}.lproj`, 'Localizable.strings')
  if (!existsSync(path)) return null
  try { return parseStrings(readFileSync(path, 'utf8')) } catch { return null }
}
