/**
 * WordPress platform support.
 * Scans PHP files for translatable strings: __(), _e(), _n(), esc_html__(), etc.
 * Generates .pot template + per-language .po files.
 *
 * This is a key Pronto differentiator — forthwith doesn't support WordPress.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs'
import { join, relative } from 'path'

export interface WpString {
  key: string
  context?: string
  plural?: string
  locations: string[]
}

// Matches: __('text', 'domain'), _e('text', 'domain'), esc_html__('text', 'domain'), etc.
const WP_I18N_RE = /(?:__|_e|_n|_x|_nx|esc_html__|esc_attr__|esc_html_e|esc_attr_e)\s*\(\s*(['"])((?:(?!\1).|\\.)*)\1/g

export function scanPhpFiles(dir: string): WpString[] {
  const found = new Map<string, WpString>()

  function scanDir(path: string) {
    if (!existsSync(path)) return
    for (const entry of readdirSync(path, { withFileTypes: true })) {
      if (entry.name.startsWith('.') || entry.name === 'node_modules') continue
      const fullPath = join(path, entry.name)
      if (entry.isDirectory()) {
        scanDir(fullPath)
      } else if (entry.name.endsWith('.php')) {
        const content = readFileSync(fullPath, 'utf8')
        const relPath = relative(dir, fullPath)
        for (const match of content.matchAll(WP_I18N_RE)) {
          const text = match[2].replace(/\\'/g, "'").replace(/\\"/g, '"')
          if (!text.trim()) continue
          const lineNum = content.slice(0, match.index).split('\n').length
          if (found.has(text)) {
            found.get(text)!.locations.push(`${relPath}:${lineNum}`)
          } else {
            found.set(text, { key: text, locations: [`${relPath}:${lineNum}`] })
          }
        }
      }
    }
  }

  scanDir(dir)
  return Array.from(found.values())
}

export function generatePot(strings: WpString[], domain: string, projectName: string): string {
  const now = new Date().toISOString()
  const lines = [
    `# ${projectName}`,
    `# Generated by Pronto CLI`,
    `msgid ""`,
    `msgstr ""`,
    `"Project-Id-Version: ${domain}\\n"`,
    `"POT-Creation-Date: ${now}\\n"`,
    `"MIME-Version: 1.0\\n"`,
    `"Content-Type: text/plain; charset=UTF-8\\n"`,
    `"Content-Transfer-Encoding: 8bit\\n"`,
    ``,
  ]

  for (const str of strings) {
    for (const loc of str.locations) lines.push(`#: ${loc}`)
    if (str.context) lines.push(`msgctxt "${escPo(str.context)}"`)
    lines.push(`msgid "${escPo(str.key)}"`)
    if (str.plural) {
      lines.push(`msgid_plural "${escPo(str.plural)}"`)
      lines.push(`msgstr[0] ""\nmsgstr[1] ""`)
    } else {
      lines.push(`msgstr ""`)
    }
    lines.push(``)
  }

  return lines.join('\n')
}

export function generatePo(strings: WpString[], translations: Record<string, string>, language: string): string {
  const lines = [
    `msgid ""`,
    `msgstr ""`,
    `"Language: ${language}\\n"`,
    `"Content-Type: text/plain; charset=UTF-8\\n"`,
    ``,
  ]
  for (const str of strings) {
    lines.push(`msgid "${escPo(str.key)}"`)
    lines.push(`msgstr "${escPo(translations[str.key] ?? '')}"`)
    lines.push(``)
  }
  return lines.join('\n')
}

function escPo(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\t/g, '\\t')
}

export function writePotFile(dir: string, domain: string, content: string): string {
  const langDir = join(dir, 'languages')
  if (!existsSync(langDir)) mkdirSync(langDir, { recursive: true })
  const path = join(langDir, `${domain}.pot`)
  writeFileSync(path, content, 'utf8')
  return path
}

export function writePoFile(dir: string, domain: string, language: string, content: string): string {
  const langDir = join(dir, 'languages')
  if (!existsSync(langDir)) mkdirSync(langDir, { recursive: true })
  const path = join(langDir, `${domain}-${language}.po`)
  writeFileSync(path, content, 'utf8')
  return path
}
